version: '3.8'
services:
  InventoryServiceMongoDB:
    image: mongo:latest
    restart: always
    ports: 
      - "27000:27017"
    networks:
      - ComputerRepairNetwork
    volumes:
      - mongo-storage:/data/db
networks:
  ComputerRepairNetwork: {}
volumes:
  mongo-storage: {}