version: '3.8'
services:
  InventoryServiceMongoDB:
    image: mongo:latest
    restart: always
    ports: 
      - "27000:27017"
    networks:
      - ComputerRepairNetwork
    volumes:
      - mongo-storage:/data/db

  InventoryServiceAPI:
    build: ./Inventory/backend/InventoryService
    image: inventoryserviceapi
    restart: always
    networks:
      - ComputerRepairNetwork
    depends_on:
      - InventoryServiceMongoDB
      - EurekaRegistry
    
  CartServiceRedisDB:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - ComputerRepairNetwork
  
  CartServiceAPI:
    build: ./Cart/backend/CartService
    image: cartserviceapi
    restart: always
    ports:
      - 8081:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - CartServiceRedisDB
      - EurekaRegistry

  RepairStoreSQLDB:
    build: ./SQL Server
    image: userservicesqldb
    restart: always
    ports:
      - 1433:1433
    networks:
      - ComputerRepairNetwork
    volumes:
      - sql-storage:/var/opt/mssql
    
  UserServiceAPI:
    build: ./User/backend/UserService
    image: userserviceapi
    restart: always
    ports:
      - 8082:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - RepairStoreSQLDB
      - EurekaRegistry

  OrderServiceAPI:
    build: ./Order/backend/OrderService
    image: orderserviceapi
    restart: always
    ports:
      - 8083:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - RepairStoreSQLDB
      - EurekaRegistry

  TicketServiceAPI:
    build: ./Ticket/backend/PRO290TicketServiceAPI
    image: ticketserviceapi
    restart: always
    ports:
      - 8084:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - RepairStoreSQLDB
      - EurekaRegistry

  EurekaRegistry:
    container_name: EurekaRegistry
    image: steeltoeoss/eureka-server:latest
    restart: always
    hostname: EurekaRegistry
    ports:
      - 8761:8761
    networks: 
      - ComputerRepairNetwork

  API-Gateway:
    container_name: api-gateway
    build: ./ApiGateway/API-Gateway
    image: springcloudapigateway
    restart: always
    ports:
      - 8080:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - EurekaRegistry
      - CartServiceAPI
      - UserServiceAPI
      - InventoryServiceAPI
      - TicketServiceAPI
      - OrderServiceAPI

networks:
  ComputerRepairNetwork: {}
volumes:
  mongo-storage: {}
  sql-storage: {}