version: '3.8'
services:
  InventoryServiceMongoDB:
    image: mongo:latest
    restart: always
    ports: 
      - "27000:27017"
    networks:
      - ComputerRepairNetwork
    volumes:
      - mongo-storage:/data/db

  InventoryServiceAPI:
    build: ./Inventory/backend/InventoryService
    image: inventoryserviceapi
    restart: always
    ports: 
      - 8080:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - InventoryServiceMongoDB
    
  CartServiceRedisDB:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - ComputerRepairNetwork
  
  CartServiceAPI:
    build: ./Cart/backend/CartService
    image: cartserviceapi
    ports:
      - 8081:8080
    networks:
      - ComputerRepairNetwork
    depends_on:
      - CartServiceRedisDB
networks:
  ComputerRepairNetwork: {}
volumes:
  mongo-storage: {}